#put specific configuration in this file
application:
  name: poc-hibernate-envers
  description: @project.description@
  version: @project.version@
  path.pkg: com.luc.api
  jenkins.build.version: @build.number@

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    properties:
      hibernate:
        format_sql: false
        order_inserts: true
        show_sql: true
        use_sql_comments: true

cors:
  enabled: true
  allowed-headers: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-origins: "*"
  exposed-headers: Content-Disposition, Content-Length, Content-Type

springdoc:
  swagger-ui:
    url: /v3/api-docs/

logging:
  config: classpath:logs/log4j2-spring.sit.xml

management:
  endpoint:
    logfile:
      external-file: /appserver/logs/${spring.application.name}/${spring.application.name}.log

reports:
  temp-output: /appserver/tmp/${spring.application.name}