server:
  port: 8081
  servlet:
    context-path: /poc-hibernate-envers

spring:
  datasource:
    username: poc-hibernate-envers
    password: poc-hibernate-envers
    hikari.pool-name: ${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/poc-hibernate-envers

#cors:
#  enabled: true
#  allowed-headers: "*"
#  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
#  allowed-origins: "*"
#  exposed-headers: Content-Disposition, Content-Length, Content-Type

springdoc:
  swagger-ui:
    url: /v3/api-docs/

logging:
  config: classpath:logs/log4j2-spring.dev.xml

management:
  endpoint:
    logfile:
      external-file: ./target/logs/${spring.application.name}.log

reports:
  temp-output: ./target/tmp/${spring.application.name}