#put specific configuration in this file
application:
  name: poc-hibernate-envers
  description: @project.description@
  version: @project.version@
  path.pkg: com.luc.api
  jenkins.build.version: @build.number@

spring:
  application:
    name: poc-hibernate-envers
  profiles:
    active: @activeProfile@

  #JPA
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    format_sql: false
    open-in-view: false
    order_inserts: true
    use_sql_comments: true
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update

    properties:
      hibernate:
        hql:
          bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsOrClauseBulkIdStrategy

      org.hibernate.envers.audit_table_suffix: _AUDITED
      org.hibernate.envers.revision_field_name: REV
      org.hibernate.envers.revision_type_field_name: REVTYPE

springdoc:
  show-actuator: true
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: [ 'health', 'info', 'logfile' ]
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    logfile:
      enabled: true


cloud:
  aws:
    stack:
      auto: false
    credentials:
      access-key: put-your-access-key-here
      secret-key: put-your-secret-key
    region:
      static: sa-east-1
      auto: false
      use-default-aws-region-chain: true
    s3:
      bucketName: put-your-bucket-name-here